account/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home,name="home"),
    path('signup', views.signup,name='signup'),
    path('login', views.user_login,name='login'),
    path('logout', views.user_logout,name='logout'),

]

socialite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django_private_chat import urls as django_private_chat_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls'), name="account_app"),
    path('userpage/', include('userpage.urls'), name="userpage_app"),
    
    
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

userpage/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from .views import Search_User


urlpatterns = [
    path('', views.userHome, name="userHome"),
    path('post', views.post, name="post"),
    path('like', views.likepost, name="likepost"),
    path("delete/<int:ID>", views.delpost, name="delpost"),
    path("profile/<str:username>", views.userProfile, name="userprofile"),
    path("chat/<str:userchat>", views.talkmain, name="talk"),
    path('comment/<int:post_id>',views.comment, name="comment"),
    path('user/follow/<str:username>', views.follow, name = 'follow'),
    path('search', Search_User.as_view(), name = 'search_user'),
    path('profile_change', views.profile_change, name = 'profile_change'),
    path('about', views.about, name = 'about'),
    path('story', views.story, name = 'story'),
    



    #path('messages/<int:chatroom>', views.talkmessages, name="messages"),


    #chat
    
    
    

]

userpage/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    caption = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='Post')

    def __str__(self):
        return str(self.user) + ' from ' + str(self.caption) + "-" + str(self.date)


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    userImage = models.ImageField(
        upload_to='Profile', default="default/default.png")
    bio = models.CharField(max_length=200)
    connection = models.CharField(max_length=100, blank=True)
    follower = models.IntegerField(default=0)
    following = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)


class Like(models.Model):
    user = models.ManyToManyField(User, related_name='LikingPost')
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    #likes = models.IntegerField(default = 0)

    @classmethod
    def liked(cls, post, liking_user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.add(liking_user)

    @classmethod
    def dislike(cls, post, disliking_user):
        obj, create = cls.objects.get_or_create(post=post)
        obj.user.remove(disliking_user)

    def __str__(self):
        return str(self.post)


# chat system:
class ChatRoom(models.Model):
    #user_requested = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_reqed')
    #user_requesting = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_reqing')
    owner = models.CharField(max_length=900)
    chatter1 = models.CharField(max_length=200)

    def __str__(self):
        return str(self.owner)


class Chat(models.Model):
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    text = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    chatter = models.CharField(max_length=900)

    def __str__(self):
        return str(self.text)


class Comment(models.Model):
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentor = models.ForeignKey(User, on_delete=models.CASCADE)
    nestedcommentor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='nested', null=True)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text) + ' in ' + str(self.post) + ' from ' + str(self.commentor.username)

# follow models


class Following(models.Model):
    # every user will create one Following model whic will have many users whic the creating user will follow
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followed = models.ManyToManyField(User, related_name='followinguser')
    follower = models.ManyToManyField(User, related_name='followeruser')

    @classmethod
    def follow(cls, user, another_account):
        obj, create = cls.objects.get_or_create(user=user)
        obj.followed.add(another_account)
        print('followed')

    @classmethod
    def unfollow(cls, user, another_account):
        obj, create = cls.objects.get_or_create(user=user)
        obj.followed.remove(another_account)
        print('unfollowed')

    def __str__(self):
        return str(self.user)


class Story(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = image = models.ImageField(upload_to='Story')
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

userpage/views.py
from django.shortcuts import render, HttpResponse, redirect,HttpResponseRedirect 
from django.urls import reverse_lazy,reverse
#from django.contrib.humanize import naturaltime

from django.contrib.humanize.templatetags.humanize import naturaltime
from django.contrib import messages
from django.contrib.auth.models import User
from . models import Post,Profile, Like, ChatRoom, Chat, Comment, Following, Story
from django.contrib.auth.decorators import login_required
import json
from django.db.models import Max
from random import shuffle
from django.views.generic import ListView
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

# Create your views here.
@login_required(login_url='/')
def userHome(request):
    following_obj = Following.objects.get(user= request.user)
    followed_users = [i for i in following_obj.followed.all()]
    followed_users.append(request.user)
    following_users_posts = Post.objects.filter(user__in = followed_users).order_by('-date')
    chat_rooms = ChatRoom.objects.filter(owner__icontains=request.user.username).annotate(max_pub_date=Max('chat__time')).order_by('-max_pub_date')
    comments = Comment.objects.all().order_by('-time')
    #print(chat_rooms)
    profs =[]
    
    for i in chat_rooms:
        owner = i.chatter1
        #print(owner)
        chatname = str(owner).replace(request.user.username,'')
        user1 = User.objects.filter(username=chatname)
        profile1 = Profile.objects.get(user = user1[0])
        profs.append(profile1)


        
        
        
    #reccomended posts
    my_lists = Post.objects.all().difference(Post.objects.filter(user__in = followed_users))
    posts = list(my_lists)
    shuffle(posts)
    #suggested users
    sugs = Profile.objects.all().difference(Profile.objects.filter(user__in = followed_users))
    suggested_profiles = list(sugs)
    shuffle(suggested_profiles)

    
    liked_post=[]
    for i in following_users_posts:
        is_lked = Like.objects.filter(post = i, user= request.user)
        if is_lked:
            liked_post.append(i)
    stories = Story.objects.filter(user__in = followed_users).order_by('-time')
    sug_stories = Story.objects.all().difference(Story.objects.filter(user__in = followed_users))
    



    context={
        'posts':posts,
        "liked_post":liked_post,
        'profs':profs,
        'chatrooms':chat_rooms,
        'comments': comments,
        'following_users_posts':following_users_posts,
        'suggested_profiles':suggested_profiles,
        'stories':stories,
        "sug_stories":sug_stories
        

    }
    #print(liked_post)


    
    return render(request,'userpage/postfeed.html',context)

def post(request):
    if request.method =='POST':
        image_ = request.FILES['image']
        captions_ = request.POST.get('captions','')
        user_ = request.user
        print(captions_,user_)
        post_obj = Post(user=user_,caption=captions_,image=image_)
        post_obj.save()
        messages.success(request,'Post Has Been Added ')
        return redirect('/userpage')
    else:
        return redirect('/userpage')
        messages.warning(request,'Something Went Wrong')

def delpost(request, ID):
    post_ = Post.objects.filter(pk = ID)
    if post_[0].image :
        image_path = post_[0].image.url # image path to delete

    
    post_.delete()
    messages.info(request,"Post Deleted")
    return redirect('/userpage')
@login_required(login_url='/')
def userProfile(request, username):
    user = User.objects.filter(username=username)
    if user:
        profile = Profile.objects.get(user = user[0])
        post_obj = Post.objects.filter(user= user[0]).order_by('-date')
        is_following = Following.objects.filter(user = request.user, followed = user[0])
        followings = Following.objects.get(user = user[0])
        followings_no = followings.followed.count()
        followers_no = followings.follower.count()
        print(followers_no)


        #for mutual followers
        """
        followers1 = Following.objects.filter(followed= request.user)
        followers2 = Following.objects.filter(followed = user)
        mutuals =  followers1.intersection(followers2)
        print(mutuals)
        """

        #post = getPost(user)
        context = {
            'profile':profile,
            'posts':post_obj,
            'is_following':is_following,
            'followings_no': followings_no,
            'followers_no':followers_no

        }
        return render(request, 'userpage/userProfile.html',context)
    else:
        messages.warning(request, 'User Does Not Exist')
        return redirect('/userpage')





def likepost(request):
    post_id = request.GET.get("likeid","")
    #print(id)
    post = Post.objects.get(pk = post_id)
    user = request.user
    like = Like.objects.filter(post=post, user=user)
    liked_track = False
    
    #Like.liked(post,user)
    #check if like exists
    if like:
        
        Like.dislike(post,user)
    else:
        liked_track= True
        Like.liked(post,user)
    resp = {
        'liked_track':liked_track
    }
    response = json.dumps(resp)
    




    return HttpResponse(response,content_type='application/json')


#chatroom
@login_required(login_url='/')
def talkmain(request,userchat):
    print(userchat)
    print(request.user)
    name_1 = userchat + request.user.username
    name_2 = request.user.username + userchat
    name = name_1 + name_2
    print(name)
    user = User.objects.filter(username=userchat)
    profile = Profile.objects.get(user = user[0])
    #chatroom = ChatRoom.objects.get_or_create(
        #owner=name
    #)
    if ChatRoom.objects.filter(owner__icontains=name_1).union(ChatRoom.objects.filter(owner__icontains=name_2)):
        chatroom_created = ChatRoom.objects.filter(owner__icontains=name_1).union(ChatRoom.objects.filter(owner__icontains=name_2))[0]
    else:
        chatroom_save = ChatRoom(owner=name, chatter1=name_1)
        chatroom_save.save()
        chatroom_created = ChatRoom.objects.filter(owner__icontains=name_1).union(ChatRoom.objects.filter(owner__icontains=name_2))[0]



    
    msgs = Chat.objects.filter( room=chatroom_created.pk).order_by('-time')
    if request.method == 'POST':
        text = request.POST['messages1']
        #room = request.POST['room']
        chatter = request.POST['chatter']
        msg = Chat(text=text, room = chatroom_created, chatter=chatter)
        
        msg.save()
        
    
    return render(request, 'chatroom/talk.html',{'userchat':userchat,'user':user, 'profile':profile, 'chatroom':chatroom_created,'msgs':msgs})




#comment fun
def comment(request,post_id):
    if request.method == 'POST':
        comment_ = request.POST.get('text')
        nested_ = request.POST.get('nested_commentor')
        post_ = Post.objects.get(pk = post_id)

        comment_obj = Comment(text=comment_,commentor=request.user,nestedcommentor=nested_,post=post_)
        comment_obj.save()
        
        
    return redirect('/userpage')


# follow
def follow(request,username):
    main_user = request.user
    to_follow = User.objects.get(username = username)
    #check if user followed already
    following = Following.objects.filter(user =main_user , followed = to_follow)
    if following:
        is_following = True
    else:
        is_following = False
    if is_following:
        Following.unfollow(main_user, to_follow)
        is_following = False
    else:
        Following.follow(main_user, to_follow)
        is_following =True
    resp = {
        'following':is_following,
    }
    response = json.dumps(resp)
    return HttpResponse(response , content_type = 'application/json')


#using class based views for searching users



class Search_User(ListView):
    model = User
    template_name = "userpage/search_user.html"
    def get_queryset(self):
        username = self.request.GET.get('username', '')
        search_results = User.objects.filter(username__icontains = username)
        print(username)
        print(search_results)
        return search_results
        


#Profile Change


def profile_change(request):
    if request.method == 'POST':
        bio = request.POST.get('bio_')
        image = request.FILES.get('image')
        link = request.POST.get('link_')
        if bio:
            prof1 = Profile.objects.get(user = request.user)
            prof1.bio = bio
            prof1.save()
            print('Bio Updated')
            
        if image:
            prof2 = Profile.objects.get(user = request.user)
            prof2.userImage = image
            prof2.save()
            print('DP Updated')

            
        if link:
            prof3 =Profile.objects.get(user = request.user)
            prof3.connection = link
            prof3.save()
            print('Link Updated')
    return HttpResponseRedirect(reverse('userprofile', args=[str(request.user)]))




def about(request):
    if request.method =="POST":
        email = request.POST.get('email')
        issue = request.POST.get('issue')
        text = request.POST.get('text')
        messages.success(request,'Your Message Sent Successfully')
        print(email)
        print(issue)
        print(text)
        #email to Admin
        template1 = render_to_string('con1.html', { 'email': email, "message":text, "issue":issue})
        email1 = EmailMessage(
            email + ' Has Gave Us Feedback',
            template1,
            settings.EMAIL_HOST_USER,
            ['debroyshayan@gmail.com'],

            )
        email1.fail_silently = False
        email1.send()
        
         

        #email to user

        template2 = render_to_string('con2.html', { 'email': email, "message":text, "issue":issue})
        email2 = EmailMessage(
            email + ' , We Received You Feedback',
            template2,
            settings.EMAIL_HOST_USER,
            [email],

            )

templates/userpage/comments.html
{% extends "base.html" %}
{% block body %}
<form>
  <div class="container">


    <div class="form-group row">

    </div>
    <div class="form-group row">
      <label for="comment_text" class="col-sm-2 col-form-label">Comments</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="comment_text">
      </div>
    </div>
</form>
</div>
{% endblock body %}

templates/userpage/search_user.html
{% extends "base.html" %}
{% block body %}

<div class="container ">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h4 class="border-bottom border-gray pb-2 mb-0">Search <strong style="color:#3fc1c9 ;">Results :</strong></h4>
    {% for i in object_list %}
    <div class="media text-muted pt-3">
      <a style="text-decoration: none;" href="{% url 'userprofile' i.username  %}"> <img
          style="height: 3.2em; margin-bottom: .5em;" class="bd-placeholder-img mr-2 rounded"
          src="{{i.profile_set.first.userImage.url}}" alt="">

        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <div class="d-flex justify-content-between align-items-center w-60">
            <strong class="text-gray-dark">Sinup@{{i.username}}</strong>
            <a href="{% url 'userprofile' i.username  %}">Visit</a>
          </div>
          <span class="d-block">Username: {{i.first_name}}</span>
          <p>Followers: </strong>{{i.followers_no}} <strong style="margin-left: .5em;">
              Following:</strong> {{i.followings_no}}
        </div>
        </p>

      </a>
    </div>
    {% endfor %}

  </div>
</div>
{% endblock body %}

templates/userpage/storytest.html
{% load static %}
{% load humanize %}

<html>
  <head>
    <title>zuck.js</title>

    <link rel="icon" href="ICON.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />

    <!-- demo styles -->
    <link rel="stylesheet" href="{% static 'userpage/zuck.js-master/demo/style.css' %}">

    <!-- lib styles -->
    <link rel="stylesheet" href="{% static 'userpage/zuck.js-master/dist/zuck.min.css' %}">
    
    <!-- lib skins -->
    <link rel="stylesheet" href="{% static 'userpage/zuck.js-master/dist/skins/snapgram.css' %}">
    <link rel="stylesheet" href="{% static 'userpage/zuck.js-master/dist/skins/vemdezap.css' %}">
    <link rel="stylesheet" href="{% static 'userpage/zuck.js-master/dist/skins/facesnap.css' %}">
    <link rel="stylesheet" href="{% static 'userpage/zuck.js-master/dist/skins/snapssenger.css' %}">
  </head>

  <body>
    <h1 id="header">&nbsp;</h1>

    <a href="https://ramon.codes/projects/zuck.js" target="_blank" class="disclaimer">
      <img src="ICON.png" alt="zuck.js logo" />

      <p>This a demonstration of <strong>zuck.js</strong> javascript library.</p>
      <p>Not associated with Facebook, Instagram, WhatsApp or Snapchat.</p>
    </a>

    <div id="stories" class="storiesWrapper"></div>

    <div class="skin">
      Choose your theme:

      <select id="skin" onchange="changeSkin(this.options[this.selectedIndex].value);">
        <option value="Snapgram">Snapgram (without fullscreen)</option>
        <option value="FaceSnap">FaceSnap (with fullscreen)</option>
        <option value="VemDeZAP">VemDeZAP (timeline + arrows)</option>
        <option value="Snapssenger">Snapssenger (with previews)</option>
      </select>
    </div>

    <script src="{% static 'userpage/zuck.js-master/dist/zuck.min.js' %}"></script>
    <script src="{% static 'userpage/zuck.js-master/demo/script.js' %}"></script>

    <script>
      var currentSkin = getCurrentSkin();
      var stories = new Zuck('stories', {
        backNative: true,
        previousTap: true,
        skin: currentSkin['name'],
        autoFullScreen: currentSkin['params']['autoFullScreen'],
        avatars: currentSkin['params']['avatars'],
        paginationArrows: currentSkin['params']['paginationArrows'],
        list: currentSkin['params']['list'],
        cubeEffect: currentSkin['params']['cubeEffect'],
        localStorage: true,
        stories: [
           
          {% for i in stories %}
          Zuck.buildTimelineItem(
            "{{i.user}}",
            "{{i.user.profile_set.first.userImage.url}}",
            "{{i.user}}",
            "",
            timestamp(),
            [
              ["{{i.pk}}", "photo", 4, "{{i.image.url}}", "{{i.image.url}}", '', false, false, timestamp()],
              ["gorillaz-2", "photo", 3, "https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/5.jpg", "https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/5.jpg", '', false, false, timestamp()],
            ]
          ),{% endfor %}
          
          
          
        ]
      });
    </script>
  </body>
</html>